<?php
// Automatically Generated by TestLink Installer - Wed, 17 Jan 18 21:21:09 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlinkti');
define('DB_PASS', 'DTWYgh!@DW@#');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlinkti');
define('DB_TABLE_PREFIX', '');
